language: ruby

rvm:
  - 2.5.1
  - 2.4.4
  - 2.3.7
  - 2.2.10
  - 2.1.10
  - 2.0.0-p648

gemfile:
  - gemfiles/active_record_edge.gemfile
  - gemfiles/active_record_52.gemfile
  - gemfiles/active_record_51.gemfile
  - gemfiles/active_record_42.gemfile
  - gemfiles/active_record_32.gemfile

sudo: false
services:
  - postgresql

before_install:
  - 'gem update bundler --no-document'
before_script:
  - 'bundle exec ruby bin/db_setup.rb'
script:
  - 'bundle exec rubocop'
  - 'bundle exec rspec'
after_success:
  - 'bundle exec codeclimate-test-reporter'

cache: bundler

matrix:
  exclude:
    - rvm: 2.0.0-p648
      gemfile: gemfiles/active_record_51.gemfile
    - rvm: 2.0.0-p648
      gemfile: gemfiles/active_record_52.gemfile
    - rvm: 2.0.0-p648
      gemfile: gemfiles/active_record_edge.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/active_record_51.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/active_record_52.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/active_record_edge.gemfile
    - rvm: 2.2.10
      gemfile: gemfiles/active_record_32.gemfile
    - rvm: 2.2.10
      gemfile: gemfiles/active_record_51.gemfile
    - rvm: 2.2.10
      gemfile: gemfiles/active_record_52.gemfile
    - rvm: 2.2.10
      gemfile: gemfiles/active_record_edge.gemfile
    - rvm: 2.3.7
      gemfile: gemfiles/active_record_32.gemfile
    - rvm: 2.3.7
      gemfile: gemfiles/active_record_42.gemfile
    - rvm: 2.3.7
      gemfile: gemfiles/active_record_edge.gemfile
    - rvm: 2.4.4
      gemfile: gemfiles/active_record_32.gemfile
    - rvm: 2.4.4
      gemfile: gemfiles/active_record_42.gemfile
    - rvm: 2.5.1
      gemfile: gemfiles/active_record_32.gemfile
    - rvm: 2.5.1
      gemfile: gemfiles/active_record_42.gemfile
  allow_failures:
    - rvm: 2.4.4
      gemfile: gemfiles/active_record_edge.gemfile
    - rvm: 2.5.1
      gemfile: gemfiles/active_record_edge.gemfile
